#! /bin/bash

# This script selects a random wallpaper in the ~/Pictures/Wallpapers directory and
# runs pywal on it

files = {/home/colew/Pictures/Wallpapers/*}
file = "%s\n" "${files[RANDOM % ${#files[@]}]}"
wal -a 85 -i ~/Pictures/Wallpapers/"$file"
